# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Alfa Home Daycare
email: im.makri@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Alfa daycare is a small home daycare in north seattle
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alfadaycare.com" # the base hostname & protocol for your site, e.g. http://example.com
author: "cesar romero"
twitter_username: romerocesar
github_username:  romerocesar

# analytics
analytics:
  google: "G-2CBBTSTB3F"

# plugins
plugins:
  - jekyll-remote-theme

# Build settings
# remote_theme: jekyll-agency
remote_theme: raviriley/agency-jekyll-theme
layout: home

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
