# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize the site. HTML files
# access these via {{ site.title }}, {{ site.email }}, and {{ site.variable }}.

title: Alfa Home Daycare
email: im.makri@gmail.com
description: >-
  Alfa daycare is a small home daycare in north seattle
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alfadaycare.com"
author: "cesar romero"
twitter_username: romerocesar
github_username:  romerocesar

# analytics
analytics:
  google: "G-2CBBTSTB3F"

# plugins
plugins:
  - jekyll-remote-theme

# Build settings
# remote_theme: jekyll-agency
remote_theme: raviriley/agency-jekyll-theme
layout: home

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
